name: Trigger auto deployment for assignment-app

on:
  push:
    branches: 
      - main
    paths:
      - '**'
      - '.github/workflows/assignment-app-AutoDeployTrigger-95db86b2-a8f0-43c3-9dc3-9bd65271dc69.yml'

  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ASSIGNMENTAPP_AZURE_CREDENTIALS }}

      - name: Retrieve and print secret from Azure Key Vault
        run: |
          az keyvault secret show --vault-name assignment-app-keyvault --name sql-connection-string --query value -o tsv

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: docker.io
          registryUsername: ${{ secrets.ASSIGNMENTAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ASSIGNMENTAPP_REGISTRY_PASSWORD }}
          containerAppName: assignment-app
          resourceGroup: osher-rg
          imageToBuild: oshericko/assignment-app:${{ github.sha }}
