name: Trigger auto deployment for assignment-app

on:
  push:
    branches: 
      - main
    paths:
      - '**'
      - '.github/workflows/assignment-app-AutoDeployTrigger-a1068a1d-09b3-4eda-9069-1d959872d00c.yml'
  workflow_dispatch:
      
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure CLI Login
        run: az login -u devops@ubtechservices.onmicrosoft.com -p M1m2m3m4

      - name: Retrieve secret from Azure Key Vault
        id: get_secret
        run: echo "::set-output name=secret::$(az keyvault secret show --vault-name assignment-app-keyvault1 --name sql-connection-string --query value -o tsv)"

      - name: Build container image
        run: |
          echo $SECRET
          docker build --build-arg SQL_CONNECTION_STRING="${SECRET}" -t oshericko/assignment-app:${{ github.sha }} .
        env:
          SECRET: ${{ steps.get_secret.outputs.secret }}

      - name: Log in to Docker Hub
        run: echo "${{ secrets.ASSIGNMENTAPP_REGISTRY_PASSWORD }}" | docker login -u "${{ secrets.ASSIGNMENTAPP_REGISTRY_USERNAME }}" --password-stdin

      - name: Push container image to Docker Hub
        run: docker push oshericko/assignment-app:${{ github.sha }}
