name: Trigger auto deployment for assignment-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      - main
    paths:
      - '**'
      - '.github/workflows/assignment-app-AutoDeployTrigger-a1068a1d-09b3-4eda-9069-1d959872d00c.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure CLI Login
        run: az login -u devops@ubtechservices.onmicrosoft.com -p M1m2m3m4

      - name: Retrieve and set secret from Azure Key Vault as a build argument
        run: |
          export SQL_CONNECTION_STRING=$(az keyvault secret show --vault-name assignment-app-keyvault1 --name sql-connection-string --query value -o tsv)

      - name: Build container image
        run: |
          docker build --build-arg SQL_CONNECTION_STRING="$SQL_CONNECTION_STRING" -t oshericko/assignment-app:${{ github.sha }} .
        
      - name: Push container image to Azure Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: docker.io
          registryUsername: ${{ secrets.ASSIGNMENTAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ASSIGNMENTAPP_REGISTRY_PASSWORD }}
          containerAppName: assignment-app
          resourceGroup: osher-rg
          imageToBuild: oshericko/assignment-app:${{ github.sha }}
