name: Trigger auto deployment for assignment-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/assignment-app-AutoDeployTrigger-08338a7f-f5e1-4a63-9063-346ec8aed553.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure CLI Login
        run: az login -u "${{secrets.AZURE_USER}}" -p "${{secrets.AZURE_PASSWORD}}"

      - name: Retrieve secret from Azure Key Vault
        id: get_secret
        run: echo "::set-output name=secret::$(az keyvault secret show --vault-name assignment-app-keyvault2 --name sql-connection-string --query value -o tsv)"

      - name: Build container image
        run: |
          docker build --build-arg SQL_CONNECTION_STRING="${SECRET}" -t oshericko/assignment-app:${{ github.sha }} .
        env:
          SECRET: ${{ steps.get_secret.outputs.secret }}

      - name: Log in to Docker Hub
        run: echo "${{ secrets.ASSIGNMENTAPP_REGISTRY_PASSWORD }}" | docker login -u "${{ secrets.ASSIGNMENTAPP_REGISTRY_USERNAME }}" --password-stdin

      - name: Push container image to Docker Hub
        run: docker push "${{ secrets.ASSIGNMENTAPP_REGISTRY_USERNAME }}"/assignment-app:${{ github.sha }}

      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          containerAppName: assignment-app
          resourceGroup: osher-rg
          imageToDeploy: oshericko/assignment-app:${{ github.sha }}

     

