name: Python Syntax Check and Create Pull Request to Main

on:
  push:
    branches:
      - development

jobs:
  syntax_check_and_create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install flake8

      - name: Run Flake8
        run: flake8 --max-line-length=150 .

      - name: Create Pull Request
        if: success() && github.ref == 'refs/heads/development'
        uses: actions/github-script@v5
        with:
          script: |
            const github = require('@actions/github');
            const octokit = github.getOctokit(process.env.GITHUB_TOKEN);
            const context = github.context;

            const { data: pullRequest } = await octokit.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Automatic PR: Fix Python syntax issues',
              head: 'development',
              base: 'main',
              body: 'Automated PR from GitHub Actions'
            });
